"""
base_rates.py — Base-rate discipline for the Transition Dynamics preregistration.

Purpose
-------
A high AUROC is not evidence of clinical utility. This module computes what a
detector of "structural transition dynamics" would actually deliver at the
event prevalences that hold in the target settings, and defines the
specificity floor required before any deployment claim may be made.

No result in this repository may be described as clinically useful unless it
clears the thresholds computed here.

Run:  python3 analysis/base_rates.py
"""

from __future__ import annotations

import math
from dataclasses import dataclass


# ----------------------------------------------------------------------------
# Core operating-characteristic arithmetic
# ----------------------------------------------------------------------------

def ppv(sens: float, spec: float, prev: float) -> float:
    """Positive predictive value from sensitivity, specificity, prevalence."""
    tp = sens * prev
    fp = (1.0 - spec) * (1.0 - prev)
    return tp / (tp + fp) if (tp + fp) > 0 else float("nan")


def npv(sens: float, spec: float, prev: float) -> float:
    tn = spec * (1.0 - prev)
    fn = (1.0 - sens) * prev
    return tn / (tn + fn) if (tn + fn) > 0 else float("nan")


def alert_rate(sens: float, spec: float, prev: float) -> float:
    """Fraction of evaluated windows that raise an alert."""
    return sens * prev + (1.0 - spec) * (1.0 - prev)


def number_needed_to_alert(sens: float, spec: float, prev: float) -> float:
    """Alerts issued per true transition detected. NNA = 1 / PPV."""
    p = ppv(sens, spec, prev)
    return float("inf") if p <= 0 else 1.0 / p


def spec_required_for_ppv(target_ppv: float, sens: float, prev: float) -> float:
    """
    Minimum specificity needed to reach target PPV at a given sensitivity
    and prevalence.  Solve  sens*prev / (sens*prev + (1-spec)(1-prev)) = target.
    """
    if not 0 < target_ppv < 1:
        raise ValueError("target_ppv must be in (0,1)")
    fp_allowed = sens * prev * (1.0 - target_ppv) / target_ppv
    spec = 1.0 - fp_allowed / (1.0 - prev)
    return spec


def prev_per_window(annual_or_period_rate: float, windows_per_period: float) -> float:
    """
    Convert an event rate over a period into a per-evaluation-window
    prevalence, assuming events are rare and approximately Poisson.
    """
    lam = -math.log(max(1e-12, 1.0 - annual_or_period_rate))
    return 1.0 - math.exp(-lam / windows_per_period)


# ----------------------------------------------------------------------------
# Preregistered evaluation settings
# ----------------------------------------------------------------------------

@dataclass(frozen=True)
class Setting:
    name: str
    prev: float           # per-evaluation-window event prevalence
    windows_per_pt: float # evaluation windows per patient over the observation horizon
    horizon: str
    note: str


SETTINGS = [
    Setting(
        "ICU circulatory failure (HiRID-style, 8h horizon, 2h stride)",
        prev=0.030, windows_per_pt=36.0, horizon="~3 ICU days",
        note="Event-rich by design; the most favourable realistic setting.",
    ),
    Setting(
        "ICU sepsis onset (MIMIC-IV, 6h horizon, hourly stride)",
        prev=0.010, windows_per_pt=72.0, horizon="~3 ICU days",
        note="Label is partly a clinician decision, not a physiological state.",
    ),
    Setting(
        "Ward deterioration (rapid-response call, 12h horizon)",
        prev=0.004, windows_per_pt=28.0, horizon="~14 ward days",
        note="Where most deployed early-warning scores fail on PPV.",
    ),
    Setting(
        "Psychosis relapse (CrossCheck-style, weekly window)",
        prev=prev_per_window(0.35, 52.0), windows_per_pt=40.0, horizon="~40 weeks",
        note="35%/yr relapse rate spread over weekly evaluations.",
    ),
    Setting(
        "Depression recurrence (EMA cohort, weekly window)",
        prev=prev_per_window(0.20, 52.0), windows_per_pt=52.0, horizon="1 year",
        note="Lower base rate again; the hardest PPV problem in the set.",
    ),
]

# Operating points. AUROC is deliberately not used as the headline metric.
OPERATING_POINTS = [
    ("optimistic-literature", 0.80, 0.90),
    ("strong",                0.80, 0.95),
    ("very strong",           0.80, 0.99),
    ("near-ceiling",          0.70, 0.995),
    ("Epic Sepsis Model (observed, Wong 2021)", 0.33, 0.83),
]


def fmt(x: float, nd: int = 3) -> str:
    if x != x:
        return "n/a"
    if x == float("inf"):
        return "inf"
    return f"{x:.{nd}f}"


def main() -> str:
    out: list[str] = []
    w = out.append

    w("# Base-Rate Analysis — Transition Dynamics\n")
    w("Generated by `analysis/base_rates.py`. All figures are arithmetic "
      "consequences of sensitivity, specificity and prevalence alone.\n")

    w("\n## 1. PPV and alert burden by setting\n")
    for s in SETTINGS:
        w(f"\n### {s.name}")
        w(f"\nPer-window prevalence **{fmt(s.prev,4)}** · "
          f"{s.windows_per_pt:.0f} windows per patient over {s.horizon}.  ")
        w(f"_{s.note}_\n")
        w("| Operating point | Sens | Spec | PPV | NNA | Alerts/patient | False alerts/patient |")
        w("|---|:--:|:--:|:--:|:--:|:--:|:--:|")
        for label, se, sp in OPERATING_POINTS:
            p = ppv(se, sp, s.prev)
            nna = number_needed_to_alert(se, sp, s.prev)
            ar = alert_rate(se, sp, s.prev) * s.windows_per_pt
            fa = (1.0 - sp) * (1.0 - s.prev) * s.windows_per_pt
            w(f"| {label} | {se:.2f} | {sp:.3f} | **{fmt(p)}** | {fmt(nna,1)} "
              f"| {ar:.2f} | {fa:.2f} |")

    w("\n\n## 2. Specificity floor required to reach a usable PPV\n")
    w("Sensitivity fixed at 0.80. Entries are the **minimum specificity** "
      "required. Negative or >1 entries mean the target PPV is arithmetically "
      "unreachable at that prevalence and sensitivity.\n")
    targets = [0.10, 0.20, 0.33, 0.50]
    w("| Setting | prevalence | " + " | ".join(f"PPV≥{t:.0%}" for t in targets) + " |")
    w("|---|:--:|" + ":--:|" * len(targets))
    for s in SETTINGS:
        cells = []
        for t in targets:
            sp = spec_required_for_ppv(t, 0.80, s.prev)
            cells.append(f"{sp:.4f}" if 0 <= sp <= 1 else "**unreachable**")
        w(f"| {s.name.split('(')[0].strip()} | {fmt(s.prev,4)} | " + " | ".join(cells) + " |")

    w("\n\n## 3. Preregistered utility gate\n")
    w("A result may be reported as *detection of structural transition "
      "dynamics* on discrimination evidence alone (AUROC/AUPRC vs comparator).")
    w("\nA result may **only** be reported as a candidate for clinical "
      "deployment if, in out-of-sample validation at the setting's true "
      "prevalence, it achieves all of:\n")
    w("- PPV ≥ 0.20 (NNA ≤ 5), **and**")
    w("- alert rate ≤ 1 false alert per patient per observation horizon, **and**")
    w("- median lead time ≥ 2 h (ICU) or ≥ 7 d (psychiatric), **and**")
    w("- calibration slope in [0.8, 1.25] out of sample.\n")
    w("Section 2 shows this gate implies specificity in the 0.99+ region for "
      "every setting except event-rich ICU circulatory failure. No published "
      "early-warning system in these domains currently clears it.\n")

    w("\n## 4. Reference point\n")
    w("The Epic Sepsis Model row is not hypothetical: sens 0.33, spec 0.83, "
      "AUROC 0.63, PPV 0.12 in external validation on 38,455 hospitalisations "
      "(Wong et al., *JAMA Intern Med* 2021), while alerting on 18% of all "
      "hospitalised patients. It is included as the empirical floor that any "
      "Transition Dynamics estimator must beat before it is discussed further.\n")

    return "\n".join(out)


if __name__ == "__main__":
    print(main())
